twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        admin_name: 'Guyot Mathieu'
        admin_address: '1 avenue de Friburg 68000 Colmar'
        admin_email: 'guyotmathieu572@gmail.com'
        admin_company: 'MG Production'
        admin_telephone: '06.63.02.79.29'
        admin_siret: '83218902100021'
        admin_host: 'ionos'
        admin_code_APE: '6201Z Programmation informatique'
        price: '29,99'
        money: 'euros'
        description: 'pack de démarrage'
        quantity: '1'
        
    
when@test:
    twig:
        strict_variables: true



        