index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /profile/contact
    controller: App\Controller\DefaultController::contact

commandez:
    path: /profile/commandez
    controller: App\Controller\DefaultController::commandez

cgv:
    path: /cgv
    controller: App\Controller\DefaultController::cgv

rgpd:
    path: /rgpd
    controller: App\Controller\DefaultController::rgpd

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_user:
    path: /profile/user
    controller: App\Controller\UserController::user 

app_verify:
    path: /verifylink
    controller: App\Controller\RegistrationController::verify