index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

commandez:
    path: /commandez
    controller: App\Controller\DefaultController::commandez

cgv:
    path: /cgv
    controller: App\Controller\DefaultController::cgv

rgpd:
    path: /rgpd
    controller: App\Controller\DefaultController::rgpd

monEspace:
    path: /register
    controller: App\Controller\RegistrationController::register

verify:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail